Repository MIT-Emerging-Talent/ET6-foundations-group-12, pull requests merged in 2025-01, with the labels that each got.

#31 Pull Request: Implement Recursive Binary Search and Comprehensive Tests
  solutions/binary_search.py
  solutions/tests/test_binary_search.py
Labels: ready for review

#55 fix config error Recent changes by Evan
  .vscode/settings.json
Labels: ready for review, task for all

#60 Merge `README.md` Draft to Main Branch
  .assets/logo.png
  .ls-lint.yml
  README.md
Labels: task for all

#29 Implentation of absolute value function.
  solutions/absolute_value.py
  solutions/binary_search.py
  solutions/tests/test_absolute_value.py
Labels: ready for review

#64 Pull request for merging Modulus function
  solutions/modulus.py
  solutions/tests/test_modulus.py
Labels: ready for review

#48 PR Creation for Communication File (communication.md)
  collaboration/communication.md
Labels: documentation, help wanted, ready for review, task for all

#37 Initial Version of `learning_goals.md` File Completed
  collaboration/learning_goals.md
Labels: documentation, help wanted, ready for review, task for all

#68 PR for adding Retrospective
  collaboration/retrospective.md
Labels: documentation, task for all

#50 Initial changes to the constrains.md file
  collaboration/constraints.md
Labels: documentation, help wanted, ready for review, task for all

#57 Initial suggestions for README file inside solutions folder.
  solutions/README.md
Labels: ready for review, task for all

#72 Add Negate Function to Calculator Application
  solutions/negate.py
  solutions/tests/test_negate.py
Labels: ready for review

#62 Pull request for Merging Multiply function
  solutions/divide.py
  solutions/multiply.py
  solutions/tests/test_divide.py
  solutions/tests/test_multiply.py
Labels: ready for review
